on:
  push:
    branches:
      - main
      - feature-ecr-ecs
    
env:
  ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REGION: 'ap-southeast-2'

name: Deploy to AWS
  
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: $ACCESS_KEY_ID
        aws-secret-access-key: $SECRET_ACCESS_KEY
        aws-region: $REGION
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Deploy Terraform
      run: make
      working-directory: ./terraform
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1