on:
  push:
    branches:
      - main
      - feature-ecr-ecs

name: Deploy to AWS
  
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
        #role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        #role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
    
    - name: deploy terraform
      run: make
      working-directory: ./terraform